/* Libname Statement */
libname d '/folders/myfolders/MEGA Case/Clusterinng- K means/temp';


/*Importing Raw File*/
proc import datafile='/folders/myfolders/MEGA Case/Clusterinng- K means/CC GENERAL.csv'
out=d.credit
dbms=csv
replace;
getnames=yes;
guessingrows=max;

/****MISSING VALUE IMPUTATION***/
data d.Seg_step_1;
set d.credit;
if BALANCE=. then BALANCE=1564.47;
if BALANCE_FREQUENCY=. then BALANCE_FREQUENCY=0.8772707;
if PURCHASES=. then PURCHASES=1003.2;
if ONEOFF_PURCHASES=. then ONEOFF_PURCHASES=592.4373709;
if INSTALLMENTS_PURCHASES=. then INSTALLMENTS_PURCHASES=411.0676447;
if CASH_ADVANCE=. then CASH_ADVANCE=978.8711125;
if PURCHASES_FREQUENCY=. then PURCHASES_FREQUENCY=0.4903505;
if ONEOFF_PURCHASES_FREQUENCY=. then ONEOFF_PURCHASES_FREQUENCY=0.2024577;
if PURCHASES_INSTALLMENTS_FREQUENCY=. then PURCHASES_INSTALLMENTS_FREQUENCY=0.3644373;
if CASH_ADVANCE_FREQUENCY=. then CASH_ADVANCE_FREQUENCY=0.1351442;
if CASH_ADVANCE_TRX=. then CASH_ADVANCE_TRX=3.2488268;
if PURCHASES_TRX=. then PURCHASES_TRX=14.7098324;
if CREDIT_LIMIT=. then CREDIT_LIMIT=4494.45;
if PAYMENTS=. then PAYMENTS=1733.14;
if MINIMUM_PAYMENTS=. then MINIMUM_PAYMENTS=864.2065423;
if PRC_FULL_PAYMENT=. then PRC_FULL_PAYMENT=0.1537146;
if TENURE=. then TENURE=11.5173184;
run;


/****OUTLIER TREATMENT***/
data d.Seg_step_2;
set d.Seg_step_1;
if BALANCE>5727.53 then BALANCE=5727.53;
if BALANCE_FREQUENCY>1.3510787 then BALANCE_FREQUENCY=1.3510787;
if PURCHASES>5276.46 then PURCHASES=5276.46;
if ONEOFF_PURCHASES>3912.2173709 then ONEOFF_PURCHASES=3912.2173709;
if INSTALLMENTS_PURCHASES>2219.7438751 then INSTALLMENTS_PURCHASES=2219.7438751;
if CASH_ADVANCE>5173.1911125 then CASH_ADVANCE=5173.1911125;
if PURCHASES_FREQUENCY>1.2930919 then PURCHASES_FREQUENCY=1.2930919;
if ONEOFF_PURCHASES_FREQUENCY>0.7991299 then ONEOFF_PURCHASES_FREQUENCY=0.7991299;
if PURCHASES_INSTALLMENTS_FREQUENCY>1.1593329 then PURCHASES_INSTALLMENTS_FREQUENCY=1.1593329;
if CASH_ADVANCE_FREQUENCY>0.535387 then CASH_ADVANCE_FREQUENCY=0.535387;
if CASH_ADVANCE_TRX>16.8981202 then CASH_ADVANCE_TRX=16.8981202;
if PURCHASES_TRX>64.4251306 then PURCHASES_TRX=64.4251306;
if CREDIT_LIMIT>11772.09 then CREDIT_LIMIT=11772.09;
if PAYMENTS>7523.26 then PAYMENTS=7523.26;
if MINIMUM_PAYMENTS>5609.1065423 then MINIMUM_PAYMENTS=5609.1065423;
if PRC_FULL_PAYMENT>0.738713 then PRC_FULL_PAYMENT=0.738713;
if TENURE>14.19398 then TENURE=14.19398;
run;

/* ADING LABELS TO THE VARIABLES */
data d.Seg_step_2;
set d.Seg_step_2;
label
CUST_ID ="Credit card holder ID"
BALANCE ="Monthly average balance (based on daily balance averages)"
BALANCE_FREQUENCY ="Ratio of last 12 months with balance"
PURCHASES ="Total purchase amount spent during last 12 months"
ONEOFF_PURCHASES ="Total amount of one-off purchases"
INSTALLMENTS_PURCHASES ="Total amount of installment purchases"
CASH_ADVANCE ="Total cash-advance amount"
PURCHASES_FREQUENCY="Frequency of purchases (percentage of months with at least one purchase)"
ONEOFF_PURCHASES_FREQUENCY ="Frequency of one-off-purchases"
PURCHASES_INSTALLMENTS_FREQUENCY ="Frequency of installment purchases"
CASH_ADVANCE_FREQUENCY ="Cash-Advance frequency"
AVERAGE_PURCHASE_TRX="Average amount per purchase transaction"
CASH_ADVANCE_TRX ="Average amount per cash-advance transaction"
PURCHASES_TRX ="Average amount per purchase transaction"
CREDIT_LIMIT ="Credit limit"
PAYMENTS ="Total payments (due amount paid by the customer to decrease their statement balance) in the period"
MINIMUM_PAYMENTS=" Total minimum payments due in the period."
PRC_FULL_PAYMENT ="Percentage of months with full payment of the due statement balance"
TENURE ="Number of months as a customer"
;
run;

/*** VARIABLE COPY***/
data d.Seg_step_3;
set d.Seg_step_2;
z_ONEOFF_PURCHASES=ONEOFF_PURCHASES;
z_ONEOFF_PURCHASES_FREQUENCY=ONEOFF_PURCHASES_FREQUENCY;
z_PURCHASES=PURCHASES;
z_PAYMENTS=PAYMENTS;
z_PURCHASES_INSTALLMENTS_FREQ=PURCHASES_INSTALLMENTS_FREQUENCY;
z_INSTALLMENTS_PURCHASES=INSTALLMENTS_PURCHASES;
z_PURCHASES_FREQUENCY=PURCHASES_FREQUENCY;
z_PURCHASES_TRX=PURCHASES_TRX;
z_CASH_ADVANCE_TRX=CASH_ADVANCE_TRX;
z_CASH_ADVANCE_FREQUENCY=CASH_ADVANCE_FREQUENCY;
z_CASH_ADVANCE=CASH_ADVANCE;
z_BALANCE=BALANCE;
z_MINIMUM_PAYMENTS=MINIMUM_PAYMENTS;
z_CREDIT_LIMIT=CREDIT_LIMIT;
z_PRC_FULL_PAYMENT=PRC_FULL_PAYMENT;
z_BALANCE_FREQUENCY=BALANCE_FREQUENCY;
z_TENURE=TENURE;
RUN;

/****STANDARDIZING OF VARIABLES***/
proc standard data=d.seg_step_3
mean=0 std=1 
out=d.seg_step_4;
var
z_ONEOFF_PURCHASES
z_ONEOFF_PURCHASES_FREQUENCY
z_PURCHASES
z_PAYMENTS
z_PURCHASES_INSTALLMENTS_FREQ
z_INSTALLMENTS_PURCHASES
z_PURCHASES_FREQUENCY
z_PURCHASES_TRX
z_CASH_ADVANCE_TRX
z_CASH_ADVANCE_FREQUENCY
z_CASH_ADVANCE
z_BALANCE
z_MINIMUM_PAYMENTS
z_CREDIT_LIMIT
z_PRC_FULL_PAYMENT
z_BALANCE_FREQUENCY
z_TENURE
;
run;


/****VARIABLE REDUCTION from Factor Analysis***/
ods html file='/folders/myfolders/MEGA Case/Clusterinng- K means/temp/factor_analysis.xls';
PROC FACTOR data=d.seg_step_4
METHOD=principal SCREE MINEIGEN=0 NFACTOR=6 ROTATE=varimax REORDER OUT=factor;
var 
ONEOFF_PURCHASES
ONEOFF_PURCHASES_FREQUENCY
PURCHASES
PAYMENTS
CREDIT_LIMIT
PURCHASES_INSTALLMENTS_FREQUENCY
PURCHASES_FREQUENCY
INSTALLMENTS_PURCHASES
PURCHASES_TRX
CASH_ADVANCE_TRX
CASH_ADVANCE_FREQUENCY
CASH_ADVANCE
MINIMUM_PAYMENTS
BALANCE
PRC_FULL_PAYMENT
TENURE
BALANCE_FREQUENCY
;
run;
/* factor analysis using n factor 6 as eigen value is best there*/
ods html close;

/* Assigning Cluster Membership Numbers */
proc fastclus 
data=D.seg_step_4
out=D.seg_step_5
maxclusters=3
cluster=clus_K3 
maxiter=100 ;
var
z_CASH_ADVANCE
z_CASH_ADVANCE_TRX
z_CASH_ADVANCE_FREQUENCY
z_ONEOFF_PURCHASES
z_PURCHASES
z_ONEOFF_PURCHASES_FREQUENCY
z_PAYMENTS
z_CREDIT_LIMIT
z_PURCHASES_INSTALLMENTS_FREQ
z_PURCHASES_FREQUENCY
z_INSTALLMENTS_PURCHASES
z_PURCHASES_TRX
z_MINIMUM_PAYMENTS
z_BALANCE
;
run;

proc fastclus 
data=D.seg_step_5
out=D.seg_step_5
maxclusters=4
cluster=clus_K4 
maxiter=100 ;
var
z_CASH_ADVANCE
z_CASH_ADVANCE_TRX
z_CASH_ADVANCE_FREQUENCY
z_ONEOFF_PURCHASES
z_PURCHASES
z_ONEOFF_PURCHASES_FREQUENCY
z_PAYMENTS
z_CREDIT_LIMIT
z_PURCHASES_INSTALLMENTS_FREQ
z_PURCHASES_FREQUENCY
z_INSTALLMENTS_PURCHASES
z_PURCHASES_TRX
z_MINIMUM_PAYMENTS
z_BALANCE
;
run;

proc fastclus 
data=D.seg_step_5
out=D.seg_step_5
maxclusters=5
cluster=clus_K5
maxiter=100 ;
var
z_CASH_ADVANCE
z_CASH_ADVANCE_TRX
z_CASH_ADVANCE_FREQUENCY
z_ONEOFF_PURCHASES
z_PURCHASES
z_ONEOFF_PURCHASES_FREQUENCY
z_PAYMENTS
z_CREDIT_LIMIT
z_PURCHASES_INSTALLMENTS_FREQ
z_PURCHASES_FREQUENCY
z_INSTALLMENTS_PURCHASES
z_PURCHASES_TRX
z_MINIMUM_PAYMENTS
z_BALANCE
;
run;

proc fastclus 
data=D.seg_step_5
out=D.seg_step_5
maxclusters=6
cluster=clus_K6
maxiter=100 ;
var
z_CASH_ADVANCE
z_CASH_ADVANCE_TRX
z_CASH_ADVANCE_FREQUENCY
z_ONEOFF_PURCHASES
z_PURCHASES
z_ONEOFF_PURCHASES_FREQUENCY
z_PAYMENTS
z_CREDIT_LIMIT
z_PURCHASES_INSTALLMENTS_FREQ
z_PURCHASES_FREQUENCY
z_INSTALLMENTS_PURCHASES
z_PURCHASES_TRX
z_MINIMUM_PAYMENTS
z_BALANCE
;
run;

proc fastclus 
data=D.seg_step_5
out=D.seg_step_5
maxclusters=7
cluster=clus_K7
maxiter=100 ;
var
z_CASH_ADVANCE
z_CASH_ADVANCE_TRX
z_CASH_ADVANCE_FREQUENCY
z_ONEOFF_PURCHASES
z_PURCHASES
z_ONEOFF_PURCHASES_FREQUENCY
z_PAYMENTS
z_CREDIT_LIMIT
z_PURCHASES_INSTALLMENTS_FREQ
z_PURCHASES_FREQUENCY
z_INSTALLMENTS_PURCHASES
z_PURCHASES_TRX
z_MINIMUM_PAYMENTS
z_BALANCE
;
run;

proc freq data=D.seg_step_5;
table clus_K3 clus_K4 clus_K5 clus_K6 clus_K7;
run;


/* Output*/
ods html file='/folders/myfolders/MEGA Case/Clusterinng- K means/temp/Cluster.xls';
proc tabulate data=d.seg_step_5;
var
CASH_ADVANCE
CASH_ADVANCE_TRX
CASH_ADVANCE_FREQUENCY
ONEOFF_PURCHASES
PURCHASES
ONEOFF_PURCHASES_FREQUENCY
PAYMENTS
CREDIT_LIMIT
PURCHASES_INSTALLMENTS_FREQUENCY
PURCHASES_FREQUENCY
INSTALLMENTS_PURCHASES
PURCHASES_TRX
MINIMUM_PAYMENTS
BALANCE
;
class
clus_K3 clus_K4 clus_K5 clus_K6 clus_K7;
table
(
CASH_ADVANCE
CASH_ADVANCE_TRX
CASH_ADVANCE_FREQUENCY
ONEOFF_PURCHASES
PURCHASES
ONEOFF_PURCHASES_FREQUENCY
PAYMENTS
CREDIT_LIMIT
PURCHASES_INSTALLMENTS_FREQUENCY
PURCHASES_FREQUENCY
INSTALLMENTS_PURCHASES
PURCHASES_TRX
MINIMUM_PAYMENTS
BALANCE
)
*mean,ALL clus_K3 clus_K4 clus_K5 clus_K6 clus_K7;
run;
ods html close;


